sonar.projectKey=joe-tingsanchali-sonarsource_dvpwa
sonar.organization=joe-tingsanchali-sonarsource
#sonar.region=US

sonar.projectName=dvpwa
sonar.projectVersion=1.0

sonar.sources=.
sonar.tests=sonarqube_test_samples/tests

sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=sonarqube_test_samples/coverage.xml